version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    ignore:                               # バージョンアップの除外設定
      - dependency-name: actions/checkout # 除外する依存関係の名前
        versions:                         # 除外対象のバージョン
          - 4.0.0
          - 4.1.2
