changelog:
  categories:
    - title: Enhancement
      labels:
        - enhancement
  exclude:           # リリースノートの除外設定
    labels:          # ラベルの除外
      - bug
    authors:         # GitHubアカウントの除外
      - dependabot[bot]
