name: Call Greeting
on: pull_request
jobs:
  call:
    uses: ./.github/workflows/reusable-greeting.yml
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
