name: Dependabot alerts
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/vault-action@v2.7.4
        with:
          url: https://localhost:8200
          secrets: dummy
