name: Labeler
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@0776a679364a9a16110aac8d0f40f5e11009e327 # v4.0.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
