name: Labeler
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@9fcb2c2f5584144ca754f8bfe8c6f81e77753375 # v4.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
