name: Labeler
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@9fd24f1f9d6ceb64ba34d181b329ee72f99978a0 # v4.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
